name = "your-project-name"
pages_build_output_dir = "build"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]

[env.production]
  # Bind your R2 bucket. The 'binding' must be "BUCKET".
  [[env.production.r2_buckets]]
  binding = "BUCKET"
  bucket_name = "prod-r2-bucket-name" # <-- CHANGE THIS

  [env.production.vars]
    NODE_ENV = "production"
    WEBDAV_USERNAME = "username" # <-- CHANGE THIS
    WEBDAV_PASSWORD = "password" # <-- CHANGE THIS
    # Set to "1" to allow anyone to view and list files without a password.
    # Set to "0" to make all access private.
    WEBDAV_PUBLIC_READ = "0"
